services:
  maxtgfwd:
    image: ghcr.io/tapeline/maxtgfwd:latest
    environment:
      MAXTGFWD_TG_TOKEN: ${MAXTGFWD_TG_TOKEN}
      MAXTGFWD_AUTH_PHONE_NUMBER: ${MAXTGFWD_AUTH_PHONE_NUMBER}
    configs:
      - source: botcfg
        target: /app/config.yml
    networks:
      - main_network


networks:
  main_network:
    driver: bridge


configs:
  botcfg:
    file: ./config.yml
