services:
  maxtgfwd:
    build: .
    #image: ghcr.io/tapeline/maxtgfwd:latest
    configs:
      - source: botcfg
        target: /app/config.yml
    networks:
      - main_network


networks:
  main_network:
    driver: bridge


configs:
  botcfg:
    file: ../maxtgfwd-config.yml
